Switched to version 0.8.8
ERROR: Cannot install -r requirements.txt (line 2) and python-docx==0.8.7 because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested python-docx==0.8.7
    html-to-docx 0.2.3 depends on python-docx>=0.8.8
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict